export const SUPABASE_SERVER_CLIENT = Symbol('SUPABASE_SERVER_CLIENT');
export const SUPABASE_HEALTH_GATEWAY = Symbol('SUPABASE_HEALTH_GATEWAY');
export const SUPABASE_AUTH_GATEWAY = Symbol('SUPABASE_AUTH_GATEWAY');
export const SUPABASE_PROFILES_GATEWAY = Symbol('SUPABASE_PROFILES_GATEWAY');
export const SUPABASE_MODULES_GATEWAY = Symbol('SUPABASE_MODULES_GATEWAY');
export const SUPABASE_MODULE_PERMISSIONS_GATEWAY = Symbol(
  'SUPABASE_MODULE_PERMISSIONS_GATEWAY',
);
export const SUPABASE_DOCUMENTS_GATEWAY = Symbol('SUPABASE_DOCUMENTS_GATEWAY');
export const SUPABASE_INGESTION_GATEWAY = Symbol('SUPABASE_INGESTION_GATEWAY');
export const SUPABASE_RETRIEVAL_GATEWAY = Symbol('SUPABASE_RETRIEVAL_GATEWAY');
export const SUPABASE_CHAT_GATEWAY = Symbol('SUPABASE_CHAT_GATEWAY');
export const SUPABASE_FAQ_MEMORY_GATEWAY = Symbol(
  'SUPABASE_FAQ_MEMORY_GATEWAY',
);
export const SUPABASE_OPERATIONS_GATEWAY = Symbol(
  'SUPABASE_OPERATIONS_GATEWAY',
);
export const SUPABASE_CONSULTATION_CASES_GATEWAY = Symbol(
  'SUPABASE_CONSULTATION_CASES_GATEWAY',
);
export const SUPABASE_ADMIN_DASHBOARD_GATEWAY = Symbol(
  'SUPABASE_ADMIN_DASHBOARD_GATEWAY',
);
export const SUPABASE_USER_ADMINISTRATION_GATEWAY = Symbol(
  'SUPABASE_USER_ADMINISTRATION_GATEWAY',
);
export const SUPABASE_RAG_READINESS_GATEWAY = Symbol(
  'SUPABASE_RAG_READINESS_GATEWAY',
);
