export const SUPABASE_SERVER_CLIENT = Symbol('SUPABASE_SERVER_CLIENT');
export const SUPABASE_AUTH_GATEWAY = Symbol('SUPABASE_AUTH_GATEWAY');
export const SUPABASE_PROFILES_GATEWAY = Symbol('SUPABASE_PROFILES_GATEWAY');
export const SUPABASE_MODULES_GATEWAY = Symbol('SUPABASE_MODULES_GATEWAY');
export const SUPABASE_DOCUMENTS_GATEWAY = Symbol('SUPABASE_DOCUMENTS_GATEWAY');
